### ISSUE TITLE
t.me is a false-positive

### ISSUE THREAD

**Issue by mtxadmin** [mayakyler/link-shorteners#7]
Domain t.me is not an URL shortener, but Telegram (a messenger service like Whatsapp or Viber - see telegram.org) domain. It used for making links to Telegram users, groups, channel, posts.

**Comment by mtxadmin** [comment]
Telegram's t.me is NOT like Twitter's t.co. For instance, URL to some post in a channel looks like:
https://t.me/bbcrussian/64301  (post number 64301 in channel bbcrussian, yes)
https://t.me/StatistaOfficial/1991 (post number 1991 in channel StatistaOfficial)

Some post can be viewed in web version, like first, some cannot, like second, but it's definitely not an URL shortener, not at all

**Comment by mayakyler** [comment]
Got it! Will update
